name: Test Docker

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - run: docker system df
    - run: docker system prune -a --volumes -f
    - run: docker system df
