name: Node.js CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        platform: [linux, windows, macos]
        architecture: [x64, arm64]
        include:
          - platform: linux
            architecture: x64
            os: ubuntu-latest
          - platform: linux
            architecture: arm64
            os: ubuntu-24.04-arm
          - platform: windows
            architecture: x64
            os: windows-latest
          - platform: windows
            architecture: arm64
            os: windows-11-arm
          - platform: macos
            os: macos-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        architecture: ${{matrix.architecture}}
    - run: node --version
