name: Test onnxrutime cuobjdump linux

on:
  - push

jobs:
  test-onnxruntime:
    runs-on: ubuntu-latest

    steps:
      - name: Set up CUDA
        uses: Jimver/cuda-toolkit@v0.2.36
        with:
          cuda: 12.8.1
          sub-packages: '["cuobjdump"]'
          method: network

      - name: Download voicevox-onnxruntime
        run: |
          curl -fsSL https://github.com/VOICEVOX/onnxruntime-builder/releases/download/voicevox_onnxruntime-1.23.2/voicevox_onnxruntime-linux-x64-cuda-1.23.2.tgz | \
          tar -xzf -

      - name: Download org onnxruntime
        run: |
          curl -fsSL https://github.com/microsoft/onnxruntime/releases/download/v1.23.2/onnxruntime-linux-x64-gpu-1.23.2.tgz | \
          tar -xzf -

      - name: Download private onnxruntime
        run: |
          curl -fsSL https://github.com/sabonerune/onnxruntime-builder/releases/download/onnxruntime-1.23.2-preview.3/onnxruntime-linux-x64-cuda-1.23.2.tgz | \
          tar -xzf -

      - name: Show voicevox_onnxruntime dump data
        run: |
          cuobjdump --list-elf voicevox_onnxruntime-linux-x64-cuda-1.23.2/lib/libvoicevox_onnxruntime_providers_cuda.so
          echo "------"
          cuobjdump --list-ptx voicevox_onnxruntime-linux-x64-cuda-1.23.2/lib/libvoicevox_onnxruntime_providers_cuda.so

      - name: Show org_onnxruntime dump data
        run: |
          cuobjdump --list-elf onnxruntime-linux-x64-gpu-1.23.2/lib/libonnxruntime_providers_cuda.so
          echo "------"
          cuobjdump --list-ptx onnxruntime-linux-x64-gpu-1.23.2/lib/libonnxruntime_providers_cuda.so

      - name: Show org_onnxruntime dump data
        run: |
          cuobjdump --list-elf onnxruntime-linux-x64-cuda-1.23.2/lib/libonnxruntime_providers_cuda.so
          echo "------"
          cuobjdump --list-ptx onnxruntime-linux-x64-cuda-1.23.2/lib/libonnxruntime_providers_cuda.so
