name: Test onnxrutime cuobjdump

on:
  workflow_dispatch:
    inputs:
      repo:
        default: sabonerune/onnxruntime-builder
      tag:
        default: onnxruntime-1.23.2

  push:

jobs:
  test-onnxruntime:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Download onnxruntime
        run: |
          case "$RUNNER_OS" in
            Windows) os_tag=win ;;
            Linux) os_tag=linux ;;
            *)
              echo 'unexpected runner' >&2
              exit 1
              ;;
          esac
          repo=${{ inputs.repo || 'VOICEVOX/onnxruntime-builder' }}
          version=1.23.2
          tag=${{ inputs.tag || 'onnxruntime-1.23.2' }}
          release_url="https://github.com/$repo/releases/download/$tag"
          package_name="onnxruntime-$os_tag-x64-cuda-$version.tgz"
          download_url="$release_url/$package_name"
          echo "$download_url"

          mkdir -p runtime
          curl -fsSL "$download_url" | \
          tar -xz -C runtime -f -
          ls -R .

      - name: Set up CUDA
        uses: Jimver/cuda-toolkit@v0.2.36
        with:
          cuda: 12.8.1
          sub-packages: '["cuobjdump"]'
          method: network

      - name: Show org_onnxruntime dump data
        if: ${{ runner.os == 'Windows'}}
        run: |
          cuobjdump --list-elf runtime/lib/onnxruntime_providers_cuda.dll
          echo "------"
          cuobjdump --list-ptx runtime/lib/onnxruntime_providers_cuda.dll

      - name: Show org_onnxruntime dump data
        if: ${{ runner.os == 'Linux'}}
        run: |
          cuobjdump --list-elf runtime/lib/libonnxruntime_providers_cuda.so
          echo "------"
          cuobjdump --list-ptx runtime/lib/libonnxruntime_providers_cuda.so
