name: Test onnxrutime cuobjdump

on:
  workflow_dispatch:
    inputs:
      repo:
        default: sabonerune/onnxruntime-builder
      tag:
        default: onnxruntime-1.23.2
  push:

jobs:
  test-onnxruntime:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Download onnxruntime
        run: |
          case "$RUNNER_OS" in
            Windows) os_tag=win ;;
            Linux) os_tag=linux ;;
            *)
              echo 'unexpected runner' >&2
              exit 1
              ;;
          esac
          repo=${{ inputs.repo || 'VOICEVOX/onnxruntime-builder' }}
          version=1.23.2
          tag=${{ inputs.tag || 'onnxruntime-1.23.2' }}
          release_url="https://github.com/$repo/releases/download/$tag"
          package_name="onnxruntime-$os_tag-x64-cuda-$version.tgz"
          download_url="$release_url/$package_name"
          echo "$download_url"

          mkdir -p runtime
          curl -fsSL "$download_url" | \
          tar -xz -C runtime --strip-components 1 -f -
          ls -R .

      - name: Set up CUDA
        uses: Jimver/cuda-toolkit@v0.2.36
        with:
          cuda: 12.8.1
          sub-packages: '["cuobjdump"]'
          method: network

      - name: Show onnxruntime dump data
        run: |
          case "$RUNNER_OS" in
            Windows) libname=onnxruntime_providers_cuda.dll ;;
            Linux) libname=libonnxruntime_providers_cuda.so ;;
            *)
              echo 'unexpected runner' >&2
              exit 1
              ;;
          esac
          cuobjdump --list-elf "runtime/lib/$libname"
          echo "------"
          cuobjdump --list-ptx "runtime/lib/$libname"
          echo "------"
          cuobjdump --all-fatbin "runtime/lib/$libname"
