name: Test Build

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-15
          - ubuntu-22.04-arm
          - windows-11-arm
          - macos-15-intel
        python-version:
          - "3.11.9"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v7
        with:
          repository: dofuuz/python-soxr
          ref: v1.1.0
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Install soxr
        run: |
          python -m pip install --verbose .
      - name: Test with pytest
        run: |
          cd tests
          python -m pytest
