name: Test voicevox-core otool

on:
  workflow_dispatch:
    inputs:
      repo:
        description: repo
      tag:
        description: tag
  push:

jobs:
  test-onnxruntime:
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            architecture: "x64"
          - os: macos-14
            architecture: "arm64"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Download core
        run: |
          repo=${{ inputs.repo || 'VOICEVOX/voicevox_core' }}
          tag=${{ inputs.tag || '0.16.4' }}
          release_url="https://github.com/$repo/releases/download/$tag"
          package_name="voicevox_core-osx-${{ matrix.architecture }}-$tag.zip"
          mkdir -p download
          mkdir -p voicevox_core
          curl -fsSL --retry 3 --retry-delay 5 -o "download/core.zip" "$release_url/$package_name"
          7z x -tzip -ovoicevox_core download/core.zip
          ls -R .

      - name: Show otool dump data
        run: |
          find ./voicevox_core -type f -exec sh -c '
            for f do
              if file "$f" | grep -q "Mach-O"; then
                echo "=== $f ==="
                otool -l "$f" 2>/dev/null |
                  grep -A 3 -E "LC_BUILD_VERSION|LC_VERSION_MIN_"
              fi
            done
            ' sh {} +
